version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: Shyftlabs_admin
      POSTGRES_PASSWORD: Shyftlabs_admin_pw
      POSTGRES_DB: student_result_management_system

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080